name: Build & Deploy NestJS API
on:
  push:
    branches: [develop] # Update to only trigger on the develop branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21' # Update to the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy NestJS API
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: |
            # Disable host key checking for this script execution
            export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
            # Create the project directory if it doesn't exist and navigate to it
            mkdir -p ~/tasks-api && cd ~/tasks-api
            # Check if the repository has been cloned before
            if [ ! -d ".git" ]; then
              git clone --branch develop git@github.com:esinniobiwaquareeb/tasks-api.git .
            else
              git pull origin develop
            fi
            # Install Node.js and npm if not already installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            # Install PM2 if not already installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi
            # Install project dependencies and build
            npm install && npm run build
            # Start the NestJS app using PM2, restart if it already exists
            if pm2 list | grep -q "tasks-api"; then
              pm2 restart tasks-api
            else
              pm2 start dist/main.js --name "tasks-api"
            fi
            # Save the PM2 process list
            pm2 save
            echo 'Deployment successful to Digital Ocean Droplet'
